### ISSUE TITLE
Issue when combined MySQL and PostgreSQL databases together

### ISSUE THREAD

**Issue by matejkloska** [djangonauts/django-pgjson#34]
Hi,
i've ran into issue when i use JsonField/JsonBField  in my model and postgre DB connection is not set as default database connection. I use custom db router for multiple databases and everything is correctly routed.

Cause of this problem is that mysql connection (default db connection in settings) is used for parsing postgre version (check for 9.4+ version) and it crashed on regex result check.

Is it possible to fix db_type check and use proper postgre connection when it's not default one?

```
Traceback (most recent call last):
  File "./manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/PROJECT_ROOT/.env/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/PROJECT_ROOT/.env/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/PROJECT_ROOT/.env/lib/python2.7/site-packages/django/core/management/base.py", line 393, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/PROJECT_ROOT/.env/lib/python2.7/site-packages/django/core/management/base.py", line 443, in execute
    self.check()
  File "/PROJECT_ROOT/.env/lib/python2.7/site-packages/django/core/management/base.py", line 481, in check
    include_deployment_checks=include_deployment_checks,
  File "/PROJECT_ROOT/.env/lib/python2.7/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/PROJECT_ROOT/.env/lib/python2.7/site-packages/django/core/checks/model_checks.py", line 28, in check_all_models
    errors.extend(model.check(**kwargs))
  File "/PROJECT_ROOT/.env/lib/python2.7/site-packages/django/db/models/base.py", line 1181, in check
    errors.extend(cls._check_fields(**kwargs))
  File "/PROJECT_ROOT/.env/lib/python2.7/site-packages/django/db/models/base.py", line 1258, in _check_fields
    errors.extend(field.check(**kwargs))
  File "/PROJECT_ROOT/.env/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 207, in check
    errors.extend(self._check_backend_specific_checks(**kwargs))
  File "/PROJECT_ROOT/.env/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 306, in _check_backend_specific_checks
    return connection.validation.check_field(self, **kwargs)
  File "/PROJECT_ROOT/.env/lib/python2.7/site-packages/django/db/backends/mysql/validation.py", line 19, in check_field
    field_type = field.db_type(connection)
  File "/PROJECT_ROOT/.env/lib/python2.7/site-packages/django_pgjson/fields.py", line 107, in db_type
    if get_version(connection) < 90400:
  File "/PROJECT_ROOT/.env/lib/python2.7/site-packages/django/db/backends/postgresql_psycopg2/version.py", line 44, in get_version
    return _parse_version(cursor.fetchone()[0])
  File "/PROJECT_ROOT/.env/lib/python2.7/site-packages/django/db/backends/postgresql_psycopg2/version.py", line 18, in _parse_version
    major, major2, minor = VERSION_RE.search(text).groups()
AttributeError: 'NoneType' object has no attribute 'groups'
```

**Comment by niwinz** [comment]
If you are using multiple databases the both databases should be synchronized in the same way. If you are using json fields in one database, the other also should be handle it. In this case, using json fields when you have a mix with mysql,you can't use json fields because mysql does not supports it.

**Comment by tbarbugli** [comment]
this is a valid issue. You can have multiple databases (eg. Mysql and Postgresql) use the JSON field only Postgresql and still get a crash.
