### ISSUE TITLE
import_by_path is deprecated in Django 1.10

### ISSUE THREAD

**Issue by sww314** [djangonauts/django-pgjson#45]
In Django 1.10+ import_by_path is removed.

> > > from django_pgjson.fields import JsonField
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/usr/lib/python2.7/site-packages/django_pgjson/fields.py", line 21, in <module>
> > >     from django.utils.module_loading import import_by_path as import_string
> > > ImportError: cannot import name import_by_path

**Comment by carldunham** [comment]
So this is actually because of  bug in the way that Django versions are detected:

```
if django.get_version() >= "1.7":
    from django.utils.module_loading import import_string
else:
    from django.utils.module_loading import import_by_path as import_string
```

This fails for Django >= 1.10 because of the lexical compare.

**Comment by baster33** [comment]
And there is further problem with `models.SubfieldBase` which is removed in 1.10:
```
class JsonField(six.with_metaclass(models.SubfieldBase, models.Field)):
AttributeError: 'module' object has no attribute 'SubfieldBase'
```

**Comment by angrykoala** [comment]
@baster33 The fix for the second compatibility issue from here https://github.com/omab/python-social-auth/pull/813 consists on simply inherit from models.Field directly
`
class JsonField(models.Field):
`
